name: Deploy QTube

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QTube
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # - name: Checkout Fragfile
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 1
      #     repository: qw-ctf/fragfile
      #     path: fragfile

      - name: Checkout Matchstats
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: qw-ctf/matchstats
          path: matchstats

      - name: Link stuff
        run: |
          find . -not -wholename '*.git*'
          ln -s matchstats/weeklies src/matches
          ln -s fragfile/fragfile.dat static/data/fragfile.dat

      - name: Deploy QTube
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --prefix-paths