name: Deploy QTube

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QTube
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache node_modules resources
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-

      # - name: Checkout Fragfile
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 1
      #     repository: qw-ctf/fragfile
      #     path: fragfile

      - name: Checkout Matchstats
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: qw-ctf/matchstats
          path: matchstats
          lfs: true

      - name: Link stuff
        run: |
          ln -s `pwd`/matchstats src/matches
#         ln -s fragfile/fragfile.dat static/data/fragfile.dat

      - name: Deploy QTube
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
